package com.lse.admin.model.lov;

public enum Product {

  RECRUITMENT_MANAGEMENT_SOLUTION, PRACTICE_MANAGEMENT_SOLUTION, ESTIMATOR_APPLICATION, FEATURE_FLAG_PATTERN_SET, TESTING_PATTERN_SET, SECURITY_PATTERN_SET, DEPLOYMENT_PATTERN_SET, DMS

}
